### ISSUE TITLE
This project needs a new name

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/taradino#25]
And an icon, a new versioning scheme and a roadmap. 

Name suggestions:

- Tarradino
- El Oscuro (probably already taken)
- Priest Porridge
- more ideas?

**Comment by malespiaut** [comment]
I'm just commenting to let you know that I was the one who made a fork named “El Oscuro” at one point. And I would be glad that you take that name.

**Comment by fabiangreffrath** [comment]
Indeed, there's your name 😁 
https://svn.icculus.org/rott?view=rev&revision=286

**Comment by malespiaut** [comment]
That's me, indeed!

**Comment by malespiaut** [comment]
What about:

* Toblerone (“milk chocolate Triad”, but might be a legal issue)
* Civvie's favorite (youtuber Civvie 11 complained about the lack of good ROTT source port “There are like, five source ports, and they're all kind of shit.” https://www.youtube.com/watch?v=zPBKVnSv1Uc at 6:12)
* Barkie (for the Dog mode, and this port also integrates code from Woof)
* DVIP (Developers of *Very* Incredible Power. Considering how awful the source code is, I think we should think about giving ourselves this honorable mention in the long run)
* Wolf3D++ (technically not false)

**Comment by fabiangreffrath** [comment]
> * **Civvie's favorite** (youtuber Civvie 11 complained about the lack of good ROTT source port “There are like, five source ports, and they're all kind of shit.” 

Sorry, I am 40+, no chance I will include a reference to Youtube or a random Youtuber in one of my projects. 😉 

> * **Barkie** (for the Dog mode, and this port also integrates code from Woof)

Hm, I'm this context, how about "doggod"? I mean, the game has both modes. And it's a reference to some Morbid Angel lyrics:
https://youtube.com/watch?v=-XzLMZvQqlo&feature=share7 (at 1:00)

Yes, I see the irony of proving this with a Youtube link. 😁

**Comment by malespiaut** [comment]
I leave the choice of the name to you! But I must admit that I like palindromes.

**Comment by fabiangreffrath** [comment]
I'm still a bit sold to the "tarradino" idea. He is the first character in the list to choose from, and actually the only character available in the Shareware version. I don't think I have *ever* played with any other character, but who did?

**Comment by malespiaut** [comment]
To be honest, I have never felt a tremendous difference when using other characters.

Any name will be better than rottsdl2 anyway. ;-)

**Comment by fabiangreffrath** [comment]
"friar" is also a cool name. It means mir or less the same as "monk" and even looks similar to the word "triad".

**Comment by fabiangreffrath** [comment]
"Triadagio" is the first map in the `extreme.rtl` map set. Another cool name.

**Comment by Swim-Swim-Hungry** [comment]
ROTT4SDL or Rise of the SDL.

**Comment by malespiaut** [comment]
I would vote against any name that is too “FLOSS”-like, if you can see what I mean. :-P I think that it would be nice to have a name that doesn't contain “ROTT” neither “SDL”.

**Comment by malespiaut** [comment]
Now that I think about it, I remember that I've named one of my private source port attempt “Larvae”, since you need to wipe them all at the end of the game.

**Comment by fabiangreffrath** [comment]
"Larvae" is another good candidate. 
https://youtube.com/watch?v=E0jxuvYF7YM&feature=share7

**Comment by Swim-Swim-Hungry** [comment]
> I would vote against any name that is too “FLOSS”-like, if you can see what I mean. :-P I think that it would be nice to have a name that doesn't contain “ROTT” neither “SDL”.
Tom is king?

**Comment by fabiangreffrath** [comment]
Another criterion is that the name should be "googleable", i.e. it shouldn't be a phrase or be too ambiguous.

**Comment by Swim-Swim-Hungry** [comment]
> Another criterion is that the name should be "googleable", i.e. it shouldn't be a phrase or be too ambiguous.

I thought of the name "Dacote" as a reference to the Doom Bible which became ROTT and for us to remember poor Buddy Dacote, the character in the Doom Bible that only had the purpose of dying and probably not appearing in ROTT.

**Comment by malespiaut** [comment]
Well, considering that `tarradino` shows up @fabiangreffrath github repo in second place when I type it into Google, that might be the best choice we have so far.

![2023-07-29-190443_2560x1440_scrot cleaned](https://github.com/fabiangreffrath/rott/assets/76531574/d1997f04-c168-4d7e-9222-d3e4d6cd9eaf)

**Comment by fabiangreffrath** [comment]
Oh, wow! I never even realized that. Well, sometimes choices choose themselves. Or how is it called? 😁

**Comment by erysdren** [comment]
Definitely +1 for Tarradino.

**Comment by fabiangreffrath** [comment]
Now it's official: This port is named "Taradino"! :tada:
