### ISSUE TITLE
configure.ac version

### ISSUE THREAD

**Issue by jengelh** [fabiangreffrath/taradino#3]
The tags seem to go with a YYYYMMDD scheme now, but configure.ac still sets "1.1.2", which should be probably be updated to reflect the new versioning.

**Comment by fabiangreffrath** [comment]
Indeed, the 20211123 tag is really mostly a development tag and not an actual new release. Back then, when the code was hosted at icculus.org, we decided that the next version would be 1.2 and that this one needed a complete overhaul of the input handling. I am working towards this (#1), but it's far from ready yet. Once it's done I will probably do a proper release and in that course also bump the version string in configure.ac.

**Comment by fabiangreffrath** [comment]
Well, indeed there is s different version string than `1.1.2` in CMakeLists.txt now, but I'm still not sure which versioning scheme to follow. I'll probably stick to dates, though, so let's keep on mind to adjust that when trading s new release done day.
