### ISSUE TITLE
Render 80x25 VGA text mode buffers at game exit

### ISSUE THREAD

**Issue by erysdren** [fabiangreffrath/taradino#68]
the SHAREEND and REGEND WAD lumps are 80x25 VGA text buffers meant to display when the game exited back to DOS. Maybe we should find a way to display them? I think GZDoom does the same.

I started writing some code that renders those buffers to RGB images, but I haven't finished it. There may be an existing utility that does it, but I haven't found it yet.

**Comment by fabiangreffrath** [comment]
If this is the equivalent to ENDOOM in Doom, we can use libtextscreen for that, e.g.

https://github.com/fabiangreffrath/woof/blob/835603dbaa31d783988d9a8be71295e54cdb225e/src/i_endoom.c#L31-L76

**Comment by erysdren** [comment]
Yes, it's the same. I'll figure out a way to get it cleanly setup in the ROTT codebase.

**Comment by fabiangreffrath** [comment]
This is how it was *introduced* into Woof some years ago. Things have changed quite a bit since then. The most important fact is that you only need a fraction of libtextscren for this feature.

https://github.com/fabiangreffrath/woof/commit/19d3ab0ae8a8396f1784f9de448b5aa8922dd7d0
