### ISSUE TITLE
Detect ROTT data from digital storefronts

### ISSUE THREAD

**Issue by erysdren** [fabiangreffrath/taradino#71]
Here are some default *nix installation paths for ROTT on digital storefronts:

```c
const char *homepaths[] = {
	/* steam */
	"%s/.steam/steam/steamapps/common/Rise of the Triad Dark War/Rise of the Triad - Dark War/",
	"%s/.steam/steam/steamapps/common/Rise of the Triad - Ludicrous Edition/assets/",
	/* heroic */
	"%s/Games/Heroic/Rise of the Triad/data/",
	/* gog */
	"%s/.wine/dosdevices/c:/GOG Games/Rise of the Triad/",
	"%s/GOG Games/Rise of the Triad Dark War/",
	/* other */
	"%s/.local/share/games/rott"
};
```

I was thinking that these could be queried to see if they exist, and if so, add them as a data path. Not all of them at once, just the one/s that exist. The Ironwail Quake sourceport does a similar thing with the Quake and Quake Remastered data from Steam.

Not sure what to do if the user has customized it. Under Windows, you could pull registry keys to find out the Steam library locations and iterate over them (maybe the same for GOG?). These paths will also be different under Mac OSX.

**Comment by fabiangreffrath** [comment]
We could borrow some relevant code from Chocolate Doom:

https://github.com/chocolate-doom/chocolate-doom/blob/master/src/d_iwad.c

**Comment by erysdren** [comment]
I'm also looking at Ironwail:

https://github.com/andrei-drexler/ironwail/blob/master/Quake/steam.c
